{
 "title": "Azure Network Security Group (NSG) Flows",
 "description": "Network Security Group (NSG) flows",
 "tags": [
  "Azure",
  "Network",
  "Security"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nsg",
    "label": "Network Security Group",
    "query": "{\"find\":\"terms\",\"field\":\"NetworkSecurityGroup.keyword\"}"
   },
   {
    "name": "nsgrule",
    "label": "NSG Rule",
    "query": "{\"find\":\"terms\",\"field\":\"nsgRuleName.keyword\"}"
   },
   {
    "name": "sourcehost",
    "label": "Source",
    "query": "{\"find\":\"terms\",\"field\":\"sourceHost.keyword\"}"
   },
   {
    "name": "destinationhost",
    "label": "Destination",
    "query": "{\"find\":\"terms\",\"field\":\"destinationHost.keyword\"}"
   },
   {
    "name": "destinationport",
    "label": "Destination Port",
    "query": "{\"find\":\"terms\",\"field\":\"destinationPort\"}"
   },
   {
    "name": "devicedirection",
    "label": "Action",
    "query": "{\"find\":\"terms\",\"field\":\"deviceDirection.keyword\"}"
   },
   {
    "name": "deviceaction",
    "label": "Action",
    "query": "{\"find\":\"terms\",\"field\":\"deviceAction.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes and Packet flow",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes Inbound",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "alias": "Bytes Outbound",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "expression": "A['Bytes Inbound']+B['Bytes Outbound']",
       "outputMetricName": "Bytes Total",
       "periods": 7,
       "timeshiftUnit": "days"
      },
      {
       "alias": "Packets Inbound",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "alias": "Packets Outbound",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "expression": "D['Packets Inbound']+E['Packets Outbound']",
       "outputMetricName": "Total Packets",
       "periods": 7,
       "timeshiftUnit": "days"
      }
     ]
    },
    {
     "title": "Top 10 Services by Destination",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "{{term destinationPort}} ({{term destinationServiceName.keyword}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationPort",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationServiceName.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 20 Low Port Number Services by Destination",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 13, "x": 11, "y": 7 },
     "targets": [
      {
       "alias": "{{term destinationPort}} ({{term destinationServiceName.keyword}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationPort",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationServiceName.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 11, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Public IP's",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 14, "w": 11, "x": 0, "y": 17 },
     "valueName": "total",
     "targets": [
      {
       "alias": "count",
       "bucketAggs": [
        {
         "fake": true,
         "field": "geoip.latitude",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "geoip.longitude",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "geoip.city_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "!sourceLocality.keyword:private AND deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 11, "y": 23 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceAction.keyword:D AND deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 23 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceAction.keyword:A AND deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 23 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 11, "y": 25 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "sourceAddressMaliciousIP.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 25 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "destinationAddressMaliciousIP.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 25 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 11, "y": 27 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "sourceAddressTorExit.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 27 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "destinationAddressTorExit.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 27 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 11, "y": 29 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "sourceAddressStatusCake.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 29 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "DestinationAddressStatusCake.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "NSG Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Hosts by Source",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceHost.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 10 Hosts by Destination",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationHost.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 10 NSG Rules",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nsgRuleName.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Malicious/Tor Requests/Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Source Malicious IP",
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddressMaliciousIP.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "alias": "Dest Malicious IP",
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationAddressMaliciousIP.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "alias": "Src Tor Exit",
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddressTorExit.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      },
      {
       "alias": "Dest Tor Exit",
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationAddressTorExit.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top talking pairs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "sourceHost.keyword",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationAddress.keyword",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationHost.keyword",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Accept Rules",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "sourceHost.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationAddress.keyword",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationPort",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationServiceName.keyword",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "nsgRuleName.keyword",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "!deviceAction.keyword:D AND deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Deny Rules",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "sourceHost.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationAddress.keyword",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationPort",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "destinationServiceName.keyword",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "nsgRuleName.keyword",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceAction.keyword:D AND deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Flows by Direction Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "deviceDirection.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "2" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Flows by Decision Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "deviceAction.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "2" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Packets Transferred Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Inbound Packets (DtoS)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:I AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Outbound Packets (DtoS)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:O AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Inbound Packets (StoD)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:I AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Outbound Packets (StoD)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "packetsStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:O AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bytes Transferred Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Inbound Bytes (DtoS)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:I AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Outbound Bytes (DtoS)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:O AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Inbound Bytes (StoD)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:I AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      },
      {
       "alias": "Outbound Bytes (StoD)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesStoD",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:O AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction AND flowState.keyword:E",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Flows by Destination Port",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationPort",
         "id": "3",
         "settings": { "min_doc_count": 100, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bytes (D to S) transferred by port",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationPort",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytesDtoS",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND flowState.keyword:E AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Source IPs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Number of Destination IPs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 68 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "destinationAddress.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Number of Source IPs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 71 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "sourceAddress.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Destination IPs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 10 Flows by Source Port",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourcePort",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Source IPs Over Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "sourceAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "15m", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top Destination IPs Over Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "destinationAddress.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "15m", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flows Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "NetworkSecurityGroup.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "NSG Flow Log Version",
     "type": "table",
     "description": "https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "ResourceGroup.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "NetworkSecurityGroup.keyword",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "version.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "version.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    { "title": "Last Dashboard Load", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 } },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
     "repeat": "nsg",
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
     "format": "dateTimeAsUS",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 20 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
     "repeat": "nsg",
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 23 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "The difference between now and the most recent flow timestamp",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
     "format": "dateTimeFromNow",
     "valueName": "max",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "startTime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Flow State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "flowState.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "deviceDirection.keyword:$devicedirection AND NetworkSecurityGroup.keyword:$nsg AND nsgRuleName.keyword:$nsgrule AND sourceHost.keyword:$sourcehost AND destinationHost.keyword:$destinationhost AND destinationPort:$destinationport AND deviceAction.keyword:$deviceaction",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}