{
 "title": "Bitvise SFTP Logs",
 "description": "Bitvise SFTP dashboard",
 "tags": [
  "SFTP",
  "Windows",
  "ElasticSearch",
  "Bitvise"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "{\"find\":\"terms\",\"field\":\"sftp.session.virtualAccount.keyword\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\":\"terms\",\"field\":\"host.name.keyword\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Bitvise SFTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sftp.app.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "sftp.app.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bytes read/write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{term sftp.session.virtualAccount.keyword}} / Read",
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sftp.sfs.parameters.bytesRead",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term sftp.session.virtualAccount.keyword}} / Write",
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sftp.sfs.parameters.bytesWritten",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.parameters.clientVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Read/Writes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.sfs.parameters.path.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.sfs.parameters.bytesWritten",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.sfs.parameters.bytesRead",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.name.keyword:I_SFS_TRANSFER_FILE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File deletes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.sfs.parameters.path.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.name.keyword:I_SFS_REMOVE_FILE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Entry Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Log Entries" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term host.name.keyword}} Errors",
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host AND _exists_:sftp.error.message.keyword",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH Key Usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.keyAlgorithm.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.keySha256.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.method.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.keyBits.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.flags.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.authentication.keyMd5.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username AND _exists_:sftp.authentication.keyAlgorithm.keyword",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logon Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Geo Activity",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 45 },
   "valueName": "total",
   "targets": [
    {
     "alias": "count",
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.latitude",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.longitude",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Caller IP",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "remoteIP.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1000" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.country_name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "remoteIP.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "remoteIP.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      { "field": "select field", "id": "6", "type": "count" }
     ],
     "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Counts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.error.message.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rejected login attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{term sftp.authentication.virtualAccount.keyword}} / {{term sftp.parameters.failureReason.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.authentication.virtualAccount.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sftp.parameters.failureReason.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sftp.name.keyword:I_LOGON_AUTH_FAILED",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sftp.session.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accepted login attempts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{term sftp.session.virtualAccount.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.session.virtualAccount.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sftp.name.keyword:I_LOGON_AUTH_SUCCEEDED",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.name.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host AND sftp.name.keyword:I_LOGON_AUTH_*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actions over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sftp.name.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Verbose Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "SFTP Log",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "logs"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SFTP Log",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 5000 },
         "type": "raw_document"
        }
       ],
       "query": "host.name.keyword:$host AND sftp.session.virtualAccount.keyword:$username",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}