{
 "title": "Keepalived",
 "description": "Keepalived metrics for prometheus exporter: https://github.com/gen2brain/keepalived_exporter",
 "tags": [
  "keepalived",
  "prometheus"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_systemd_unit_state{name=\"keepalived.service\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keepalived@${instance}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"keepalived.service\",instance=~\"^$instance.*\", state=\"active\"} ",
     "legendFormat": "systemd status"
    },
    {
     "expr": "keepalived_up{instance=~\"^$instance.*\"}",
     "legendFormat": "keepalived internal status"
    }
   ]
  },
  { "title": "VRRP state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "State: $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_become_master{instance=~\"^$instance.*\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Status Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Keepalived Service Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keepalived_up{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "instance" },
  {
   "title": "Keepalived state over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_advert_sent{instance=~\"^$instance.*\"}[5m])>0",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "irate(keepalived_vrrp_advert_rcvd{instance=~\"^$instance.*\"}[5m])>0",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Released master",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keepalived_vrrp_release_master{instance=~\"^$instance.*\"}[$__interval])>0",
     "legendFormat": "Release MASTER"
    },
    {
     "expr": "rate(keepalived_vrrp_become_master{instance=~\"^$instance.*\"}[$__interval])>0",
     "legendFormat": "Become MASTER"
    }
   ]
  },
  {
   "title": "Keepalived Address list errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_addr_list_err{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Advertisements",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_advert_sent{instance=~\"^$instance.*\"}[1m])>0",
     "legendFormat": "{{state}} / Sent"
    },
    {
     "expr": "irate(keepalived_vrrp_advert_rcvd{instance=~\"^$instance.*\"}[1m])>0",
     "legendFormat": "{{state}} / Received"
    }
   ]
  },
  {
   "title": "TTL errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_ip_ttl_err{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Priority zero sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_pri_zero_sent{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Keepalived Advertisement interval errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_advert_interval_err{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Packet length errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_packet_len_err{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Priority zero received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_pri_zero_rcvd{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Authentication mismatch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_authtype_mismatch{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Authentication failure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_auth_failure{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Authentication invalid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_invalid_authtype{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Invalid type errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keepalived_vrrp_invalid_type_rcvd{instance=~\"^$instance.*\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}