{
 "title": "Postfix SMTP Email + OpenDKIM",
 "description": "Browse, analyze logs in Elasticsearch for Postfix mail relay and OpenDKIM",
 "tags": [
  "ElasticSearch",
  "Azure",
  "Postfix",
  "SMTP",
  "Email"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "program",
    "label": "program",
    "query": "{\"find\":\"terms\",\"field\":\"program.keyword\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\":\"terms\",\"field\":\"host.name.keyword\",\"query\":\"$program\"}"
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Email Troubleshooting",
     "type": "text",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "content": "\n------------------------------------\n# Email Troubleshooting\n------------------------------------\n\n### 3rd Party Troubleshooting tools:\n\n| Tool                                                                \t| Use                                       \t| Details                                                                                                         |\n|---------------------------------------------------------------------\t|--------------------------------------------\t|----------------------------------------------------------------------------------------------------------------\t|\n| [MX Toolbox: DNS Records](https://mxtoolbox.com/SuperTool.aspx)     \t| Retrieve customer MX, SPF and DKIM records \t| The mail server's IP address is listed in the SPF record of the domain in the SMTP envelope's mail from header \t|\n| [SPF Validation](http://www.kitterman.com/spf/validate.html)        \t| Retrieve and validate SPF records\t          | Check ````a:your.mailrelay.com```` or ````your.mailrelay.com```` is listed in their SPF records\t  |\n| [MX Toolbox: Email Headers](https://mxtoolbox.com/EmailHeaders.aspx)  | Analyse email headers                       | Paste email headers to make them readable. Can follow email flow of an email from source to destination, along with other details. Useful when a customer has supplied an email as an attachment with intact headers. |\n| [Mail Tester](https://www.mail-tester.com/)                           | Analyse email for DKIM, SPF and spam rating | Generates a single use email address. Send an email through the product to receive a score on how success email delivery will be. |\n|\n\n1. First thing to check is to see if the user has setup an SPF record that contains your mail relay server and that it is set correctly. The user should have ````a:your.mailrelay.com```` in the record. \n \nIf the user does not have an SPF record for your mail relay server they will need to whitelist ````your.mailrelay.com```` on their email endpoints. Retrieve the customers MX records to see what they are using as their endpoints where they need to whitelist our server.\n \nIf the user has successfully setup the SPF record or whitelisted the mail server the next step is to trace the emails through the system. This can be done on this Grafana dashboard.\n\n## Recommended Practice\n#### Do:\n* Recommend the user setup SPF records\n* Recommend the user setup DKIM records\n* Use ````@example.com```` or ````@example.net```` or ````@example.org```` email addresses for emails you don't want delivered as per [RFC 2606](https://tools.ietf.org/html/rfc2606)\n* Set your mail servers to discard all emails from/to the above domains"
    },
    {
     "title": "Dashboard Guide",
     "type": "text",
     "gridPos": { "h": 21, "w": 12, "x": 0, "y": 20 },
     "content": "\n------------------------------------\n# How-to troubleshoot email relaying\n------------------------------------\n\n## Data\nGrafana dashboards work best when focused on a small set of data and narrow time period as it reduces the quantity of data it needs to return.\n1. ***Limit the time data time range:*** Set the time period in the top right of the dashboard to the smallest period possible by selecting one of the pre-configured time options, or modify the ```custom range``` options.\n2. ***Add a custom filter:*** In the top right of the dashboard, add a filter by clicking ```Filters +``` for each filter you require.\n\n## Filters\nThe filter option brings back all filters available within ElasticSearch. The majority of filters for this dashboard start with ```postfix_``` and these are the only ones you will need to filter on. Filters apply to everything on the dashboard using ElasticSearch for data. If the option exists, use a filter ending with ```.keyword``` as these are indexed and return results quicker than the non-indexed alternative.\n\nWildcards can be used if you change the operator from equals ```=``` to regex ```=~```\n\nTo exclude results change the operator to one prefixed with ```!```\n\nFilter names and values autocomplete from available data as you type.\n### Popular Filters\n1. ```postfix_from.keyword```: **Email sender.** Enter an email address to display stats and logs including only this email address. e.g. ```=``` with ```user@yourdomain.com``` or ```=~``` with ```@yourdomain.com```\n2. ```postfix_to.keyword```: **Email recipient.** Same as above. \n3. ```postfix_from_domain.keyword```: **Email sender domain.** The email domain of the sender proceeding the @ symbol. e.g. ```yourdomain.com```\n4. ```postfix_to_domain.keyword```: **Email recipient domain.** The email domain of the recipient proceeding the @ symbol. e.g. ```yourdomain.com```\n5. ```postfix_queueid.keyword```: **Queue ID.** This is an internal ID to track all processes through the internal Postfix and DKIM services. By filter on this value you can see every individual step in the mail relay for a specific message. \n6. ```postfix_dkim_domain.keyword```: **DKIM domain.** The email domain with signed DKIM messages. Helpful when troubleshoot DKIM issues, or immediately after DKIM setup to confirm correct operation. Value is the domain part of an email address excluding the @ symbol. e.g. ```yourdomain.com```\n \n### Ad-hoc filtering\nYou can quickly filter from data on the majority of tables. Hover over the data cell and select ```+``` to filter on a value, or ```-``` to filter out a value. It is not always possible for all fields, so you may need to manually filter as above.\n\n-----------------\n# Additional Help\n-----------------\nContexual help is available on some panels. Look for an ```i``` in the top right corner of any panel and hover over it to display additional details.\n\nHelp improve the documention and dashboard by feeding back to [GitHub](https://github.com/bhozar/grafana-dashboards/tree/master/postfixsmtpemail_opendkim) on what would be helpful."
    },
    {
     "title": "Response Codes",
     "type": "text",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 20 },
     "content": "\n----------------------------\n# Common SMTP Response Codes\n----------------------------\nBelow are a handful of SMTP server response codes that you might see when sending email:\n\n* ```250``` – This SMTP server response simply means everything went well and your message was delivered to the recipient server.\n* ```421``` – Your message was temporarily deferred by the recipient server. This is usually a result of too many connections in a short timeframe or too many messages.\n* ```450``` – Your message was not delivered because the other user mailbox was not available. This can happen if the mailbox is locked or is not routable.\n* ```451``` – This response is sent when the message simply failed. Often times this is not caused by you, but rather because of a far-end server problem.\n* ```452``` – This kind of response is sent back when there isn’t enough system storage to send the message. Your message is deferred until storage opens up and it can then be delivered.\n* ```550``` – The message has failed because the other user’s mailbox is unavailable or because the recipient server rejected your message.\n* ```551``` – The mailbox your message was intended for does not exist on the recipient server.\n* ```552``` – The mailbox your message was sent to does not have enough storage to accept your message.\n* ```553``` – You message was not delivered because the name of the mailbox you sent to does not exist.\n* ```554``` – This is a very vague message failure response that can refer to any number of problems either on your end or with the recipient server.\n\nIf the codes above do not offer enough detail then the next two sections contains a more thorough list of codes and their meanings.\n\n\n---------------------\n# Full Response Codes\n---------------------\n\nyou can look in the message field to find the proper error code that will give you the reason for the message. Below is a list of the Standard SMTP codes and the Extended SMTP (ESMTP) codes.\n\nThe message column in the log viewer can contain both a standard and enhanced message explaining why a response was given to make advanced troubleshooting easier. Generally the text in the response should explain what has happened.\n\n--------------------------\n# Full SMTP Response Codes\n--------------------------\nThis list of codes is the standard SMTP error codes you will find in most email responses.\n\n## 200 Codes\n* ```211``` – System status / system help reply\n* ```214``` – Help message\n* ```220``` – Domain service ready\n* ```221``` – Domain service closing transmission channel\n* ```250``` – Requested mail action completed and OK\n* ```251``` – Not Local User, forward email to forward path\n* ```252``` – Cannot Verify user, will attempt delivery later\n* ```253``` – Pending messages for node started\n## 300 Codes\n* ```354``` – Start mail input; end with .\n* ```355``` – Octet-offset is the transaction offset\n## 400 Codes\n* ```421``` – Domain service not available, closing transmission channel\n* ```432``` – Domain service not available, closing transmission channel\n* ```450``` – Requested mail action not taken: mailbox unavailable. request refused\n* ```451``` – Requested action aborted: local error in processing Request is unable to be processed, try again\n* ```452``` – Requested action not taken: insufficient system storage\n* ```453``` – No mail\n* ```454``` – TLS not available due to temporary reason. Encryption required for requested authentication mechanism\n* ```458``` – Unable to queue messages for node\n* ```459``` – Node not allowed: reason\n## 500 Codes\n* ```500``` – Syntax error, command unrecognized\n* ```501``` – Syntax error in parameters or arguments\n* ```502``` – Command not implemented\n* ```503``` – Bad sequence of commands\n* ```504``` – Command parameter not implemented\n* ```510``` – Check the recipient address\n* ```512``` – Domain can not be found. Unknown host.\n* ```515``` – Destination mailbox address invalid\n* ```517``` – Problem with senders mail attribute, check properties\n* ```521``` – Domain does not accept mail\n* ```522``` – Recipient has exceeded mailbox limit\n* ```523``` – Server limit exceeded. Message too large\n* ```530``` – Access Denied. Authentication required\n* ```531``` – Mail system Full\n* ```533``` – Remote server has insufficient disk space to hold email\n* ```534``` – Authentication mechanism is too weak. Message too big\n* ```535``` – Multiple servers using same IP. Required Authentication\n* ```538``` – Encryption required for requested authentication mechanism\n* ```540``` – Email address has no DNS Server\n* ```541``` – No response from host\n* ```542``` – Bad Connection\n* ```543``` – Routing server failure. No available route\n* ```546``` – Email looping\n* ```547``` – Delivery time-out\n* ```550``` – Requested action not taken: mailbox unavailable\n* ```551``` – User not local; please try forward path\n* ```552``` – Requested mail action aborted: exceeded storage allocation\n* ```553``` – Requested action not taken: mailbox name not allowed\n* ```554``` – Transaction failed\n\n-------------------------------------\n# Full Extended SMTP (ESMTP) standards\n-------------------------------------\nThe Extended SMTP response codes work in 3 digit combinations. For example, ```5.2.1``` is a Permanent Error where the receiving email is not accepting messages. The first number is the email message status. The second 2 numbers pinpoint the exact information bout the error.\n\n* ```2``` ***Successfully sent the email.***\n* ```4``` ***Temporary problem when sending the email.*** The email server typically will try to send it again till it reaches retry timeout.\n* ```5``` ***Permanent or Fatal error.*** This can be caused by a non existent email address, DNS problem, or your email was blocked by the receiving server.\n\nBelow is a list of the Extended SMTP error codes.\n\n***Note!*** *X* can be a ``4`` or a ``5`` depending on is its Temporary or Permanent.\n\n## X.1.x Codes\n* ```X.1.0``` – Other address status\n* ```X.1.1``` – Bad destination mailbox address\n* ```X.1.2``` – Bad destination system address\n* ```X.1.3``` – Bad destination mailbox address syntax\n* ```X.1.4``` – Destination mailbox address ambiguous\n* ```X.1.5``` – Destination mailbox address valid\n* ```X.1.6``` – Mailbox has moved\n* ```X.1.7``` – Bad sender’s mailbox address syntax\n* ```X.1.8``` – Bad sender’s system address\n## X.2.x Codes\n* ```X.2.0``` – Other or undefined mailbox status\n* ```X.2.1``` – Mailbox disabled, not accepting messages\n* ```X.2.2``` – Mailbox full\n* ```X.2.3``` – Message length exceeds administrative limit\n* ```X.2.4``` – Mailing list expansion issue\n## X.3.x Codes\n* ```X.3.0``` – Other or undefined mail system status\n* ```X.3.1``` – Mail system full\n* ```X.3.2``` – System not accepting network messages\n* ```X.3.3``` – System not capable of selected features\n* ```X.3.4``` – Message too big for system\n* ```X.3.5``` – System incorrectly configured\n## X.4.x Codes\n* ```X.4.0``` – Other or undefined network or routing status\n* ```X.4.1``` – No answer from host\n* ```X.4.2``` – Bad connection\n* ```X.4.3``` – Routing server failure\n* ```X.4.4``` – Unable to route\n* ```X.4.5``` – Network congestion\n* ```X.4.6``` – Routing loop detected\n* ```X.4.7``` – Delivery time expired\n## X.5.x Codes\n* ```X.5.0``` – Other or undefined protocol status\n* ```X.5.1``` – Invalid command\n* ```X.5.2``` – Syntax error\n* ```X.5.3``` – Too many recipients\n* ```X.5.4``` – Invalid command arguments\n* ```X.5.5``` – Wrong protocol version\n## X.6.x Codes\n* ```X.6.0``` – Other or undefined media error\n* ```X.6.1``` – Media not supported\n* ```X.6.2``` – Conversion required and prohibited\n* ```X.6.3``` – Conversion required but not supported\n* ```X.6.4``` – Conversion with loss performed\n* ```X.6.5``` – Conversion failed\n## X.7.x Codes\n* ```X.7.0``` – Other or undefined security status\n* ```X.7.1``` – Delivery not authorized, message refused\n* ```X.7.2``` – Mailing list expansion prohibited\n* ```X.7.3``` – Security conversion required but not possible\n* ```X.7.4``` – Security features not supported\n* ```X.7.5``` – Cryptographic failure\n* ```X.7.6``` – Cryptographic algorithm not supported\n* ```X.7.7``` – Message integrity failure"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "stat",
   "description": "Total unique email senders.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_from.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "agenty-flowcharting-panel",
   "description": "Mail Processing Flow",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "emails",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "_exists_:postfix_status.keyword AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "before_qmgr",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_delay_before_qmgr",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "in_qmgr",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_delay_in_qmgr",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "dkimsigned",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_dkim_message.keyword:\"DKIM-Signature field added\" AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "dkimunsigned",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_dkim_message.keyword:\"no signature data\" AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "dkimerror",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_dkim_message.keyword:error* AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "conn_setup",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_delay_conn_setup",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "transmission",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_delay_transmission",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "bounced",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_status.keyword:bounced AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "deferred",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_status.keyword:deferred AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "expired",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_status.keyword:expired AND host.name.keyword:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "sent",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_status.keyword:sent AND host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total unique email recipients.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_to.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host AND host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Messages accepted by the SMTP server for destruction. Stats can come from the Blackhole SMTP service, and in same cases, the mail relay service if certain rules are matched.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "program.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "_exists_:postfix_status.keyword AND host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Messages accepted by the SMTP server for delivery.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "_exists_:postfix_status.keyword AND host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mail Process Flow Guide",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "content": "\n# Mail Process Flow\nYou are able to click on any of the boxes which have counts in to reload the page focusing on only those stats. e.g. DKIM Errors, Expired etc. \n\n1. **Total Emails:** Number of emails inbound fromselected host systems.\n2. **Before Queue Manager:** time before queue manager, including message transmission.\n3. **In Queue Manager:** time in queue manager.\n4. **DKIM Signed:** Messages which have been successfully DKIM signed.\n5. **DKIM Unsigned:** Messages which have not been DKIM signed. As DKIM is optional, not all messages are signed. Customers can request DKIM setup on their domain though support.\n6. **DKIM Error:** Messages which attempted to be DKIM signed but failed. Should be investigated as should be 0.\n7. **Connection Setup:** connection setup time including DNS, HELO and TLS.\n8. **Transmission:** message transmission time.\n9. **Deferred:** A deferred email is simply an event the server has received back from the receiving server that tells us that the receiving server has temporarily limited access to their system. It does not mean that your message will not be delivered. Rather, it is a signal that your message will not be delivered immediately. This can happen for a variety of reasons. Some of the most common reasons a message might be deferred at an inbox provider are that the inbox provider is seeing too many spam complaints for your email that has already been delivered or that the receiving server is having technical issues at that time. We will continue to try to deliver that message for you for up to 5 days. If a message to a recipient is deferred for more than the maximum period, that deferral will turn into a bounce. Otherwise, it will result in a delivery event once the the message has been accepted by the receiving server.\n10. **Expired:** Emails which have been deferred and reached the maximum period of retires.\n11. **Bounced:** Bounces occur when the receiving server returns to us a code that indicates that the reason for the refusal is a permanent issue with that server or recipient address."
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SMTP Server Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Probe Success" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "probe_success{job=\"smtp_status\", instance=~\".*:25\"} ",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Platform Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Delivery Status",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delivery Status Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "4",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delivery Status Notification(DSN) Codes",
   "type": "table",
   "description": "See ESMTP codes",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_dsn.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "postfix_status.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delivery Status Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "4",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mail Delivery Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Mail Tx Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_size",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DKIM Signed Emails",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "program.keyword:opendkim AND postfix_dkim_message.keyword:\"DKIM-Signature field added\" AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 DKIM Signed Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_dkim_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Senders",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_from.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_from.keyword:*@* AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Recipients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_to.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_to.keyword:*@* AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Sender Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_from_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_from_domain.keyword:*.* AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Recipient Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_to_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "postfix_to_domain.keyword:*.* AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Sending Servers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_client_ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Receiving Servers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_relay_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_queueid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host/Domain Summary: Message Deferred",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_from_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "postfix_delay",
       "id": "1",
       "meta": {
        "avg": true,
        "count": false,
        "max": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "settings": {},
       "type": "extended_stats"
      },
      {
       "field": "postfix_queueid.keyword",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "program.keyword:\"postfix/smtp\" AND _exists_:postfix_from_domain.keyword AND postfix_status.keyword:deferred AND host.name.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delayed Relay Hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_relay_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_delay",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delayed Sending Domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "postfix_from_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "postfix_delay",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "program.keyword:\"postfix/smtp\" AND _exists_:postfix_from_domain.keyword AND postfix_status.keyword:deferred AND host.name.keyword:$host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Entry Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Senders by message size",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_from.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "postfix_size",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "postfix_queueid.keyword",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "program.keyword:\"postfix/smtp\"  AND _exists_:postfix_from.keyword AND postfix_status.keyword:sent AND host.name.keyword:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Host/Domain Summary: Message Delivery",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_from_domain.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "postfix_delay",
         "id": "1",
         "meta": {
          "avg": true,
          "count": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "settings": {},
         "type": "extended_stats"
        },
        {
         "field": "postfix_size",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "postfix_queueid.keyword",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "program.keyword:\"postfix/smtp\" AND _exists_:postfix_from_domain.keyword AND _exists_:postfix_to_domain.keyword AND _exists_:postfix_status.keyword AND host.name.keyword:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Recipients by message size",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_to.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "postfix_size",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "postfix_queueid.keyword",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "program.keyword:\"postfix/smtp\"  AND _exists_:postfix_to.keyword AND postfix_status.keyword:sent AND host.name.keyword:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Host/Domain Summary: Messages Received",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_to_domain.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "postfix_size",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "postfix_queueid.keyword",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "program.keyword:\"postfix/smtp\" AND _exists_:postfix_from_domain.keyword AND _exists_:postfix_to_domain.keyword AND _exists_:postfix_status.keyword AND host.name.keyword:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message bounce count by sender",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_from.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:bounced AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message bounce counter by sender- Cause:Invalid SPF",
     "type": "table",
     "description": "Senders without a valid SPF record. Emails are bounced by remote servers because your mail relay is not in their SPF record.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_from.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:bounced AND postfix_smtp_response.keyword:/.*SPF.*|*.spf.*|.*Sender Policy Framework.*/ AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message bounce counter by recipient- Cause:Invalid SPF",
     "type": "table",
     "description": "Senders without a valid SPF record. Emails are bounced by remote servers because your mail relay is not in their SPF record.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_to.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:bounced AND postfix_smtp_response.keyword:/.*SPF.*|*.spf.*|.*Sender Policy Framework.*/ AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message deferred detail",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_relay_hostname.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "postfix_smtp_response.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:deferred AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message bounce detail",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_relay_hostname.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "postfix_smtp_response.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:bounced AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message sent detail",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_relay_hostname.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "postfix_smtp_response.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "postfix_status.keyword:sent AND host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "message error responses detail",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 145 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_error_response.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "host.name.keyword:$host",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SASL Authentication Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{postfix_from.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_from.keyword",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "postfix_smtp_response.keyword:SASL*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SASL Authentication Errors",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 157 },
     "targets": [
      {
       "alias": "{{postfix_from.keyword}} - {{postfix_smtp_response.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "postfix_smtp_response.keyword",
         "id": "7",
         "settings": {
          "min_doc_count": 1,
          "missing": null,
          "order": "desc",
          "orderBy": "1",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "postfix_from.keyword",
         "id": "6",
         "settings": {
          "min_doc_count": 1,
          "missing": null,
          "order": "desc",
          "orderBy": "1",
          "size": "0"
         },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "metrics": [
        {
         "field": "postfix_queueid.keyword",
         "id": "1",
         "meta": {},
         "settings": {
          "missing": null
         },
         "type": "cardinality"
        }
       ],
       "query": "postfix_smtp_response.keyword:SASL*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Email Status Logs",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 153 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1000 },
         "type": "raw_document"
        }
       ],
       "query": "program.keyword:\"postfix/smtp\" AND _exists_:postfix_from.keyword AND _exists_:postfix_to.keyword AND _exists_:postfix_status.keyword",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "OpenDKIM Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1000 },
         "type": "raw_document"
        }
       ],
       "query": "program.keyword:\"opendkim\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Verbose Logs",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 176 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1000 },
         "type": "raw_document"
        }
       ],
       "query": "program.keyword:postfix\\/*",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}