{
 "title": "Azure Activity Log",
 "tags": [
  "Azure",
  "Security",
  "Activity"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "subscriptionname",
    "label": "Subscription Name",
    "query": "{\"find\":\"terms\",\"field\":\"azure_subscription_name.keyword\"}"
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "{\"find\":\"terms\",\"field\":\"azure.subscription.keyword\",\"query\":\"azure_subscription_name.keyword:$subscriptionname\"}"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "{\"find\":\"terms\",\"field\":\"level.keyword\",\"query\":\"azure_subscription_name.keyword:$subscriptionname\"}"
   },
   {
    "name": "azureprovider",
    "label": "Provider",
    "query": "{\"find\":\"terms\",\"field\":\"azure.provider.keyword\",\"query\":\"azure_subscription_name.keyword:$subscriptionname\"}"
   },
   {
    "name": "azureresourcegroup",
    "label": "Resource Group",
    "query": "{\"find\":\"terms\",\"field\":\"azure.resource_group.keyword\",\"query\":\"azure_subscription_name.keyword:$subscriptionname\",\"query\":\"azure.provider.keyword:$azureprovider\"}"
   },
   {
    "name": "azureresource",
    "label": "Resource",
    "query": "{\"find\":\"terms\",\"field\":\"azure.resource_name.keyword\",\"query\":\"azure.resource_group.keyword:$azureresourcegroup\"}"
   },
   {
    "name": "azureuser",
    "label": "User",
    "query": "{\"find\":\"terms\",\"field\":\"identity.claims.name.keyword\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Activity Level",
   "type": "graph",
   "description": "Administrative Activity Overview",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "per 30 minutes" }
   ],
   "targets": [
    {
     "alias": "Actions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Administrative",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name.keyword",
       "id": "1",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_group.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.subscription.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Active Users",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access Requests",
   "type": "graph",
   "description": "Authorization Activity",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Success", "query": "resultType:Success" },
         { "label": "Failure", "query": "resultType:Fail" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND operationName:*LISTKEYS*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Activity Heatmap",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.provider.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Resource Groups",
   "type": "bargauge",
   "description": "Activity by Resource Group",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resource Changes",
   "type": "graph",
   "description": "Resource Creations and Deletions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "locale", "label": "Deletions/Creations" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_type.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Creations",
          "query": "identity.authorization.action:*write"
         },
         {
          "label": "Deletions",
          "query": "identity.authorization.action:*delete"
         }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 20 Resource Change Type",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Autoscale Instance Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "activity_log_Autoscale_properties.eventProperties.NewInstancesCount",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "missing": 0 },
       "type": "cardinality"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.provider.keyword:MICROSOFT.WEB",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Autoscale Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "activity_log_Autoscale_properties.eventProperties.ActiveAutoscaleProfile.Rules.ScaleAction.Direction.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "activity_log_Autoscale_properties.eventProperties.ActiveAutoscaleProfile.Rules.MetricTrigger.Name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.category.keyword:Autoscale",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Activity Log Viewer",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "7",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "fake": true,
       "field": "azure.provider.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "30"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "11",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "30"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_name.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "30"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "resultDescription.keyword",
       "id": "13",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "30"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "resultType.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "durationMs",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed Activities",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_document"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND level:/error|critical|warning/ AND _exists_:activity_log_Administrative_properties.statusMessage",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Activated", "query": "resultType:Active" },
         { "label": "Resolved", "query": "resultType:Resolved" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:ServiceHealth",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Activated", "query": "resultType:Active" },
         {
          "label": "Resolved or Succeeded",
          "query": "resultType:Resolved OR resultType:Succeeded"
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:ServiceHealth AND resultType:Active",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:ServiceHealth AND resultType:Resolved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Activated",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Resolved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Succeeded",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Service Health Viewer",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "metrics": [
      {
       "field": "durationMs",
       "id": "6",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:ServiceHealth",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "User Activity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none", "label": "per 30 minutes" }
   ],
   "targets": [
    {
     "alias": "Actions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Administrative AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resource Changes",
   "type": "graph",
   "description": "Resource Creations and Deletions",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "locale", "label": "Deletions/Creations" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_type.keyword",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Creations",
          "query": "identity.authorization.action:*write"
         },
         {
          "label": "Deletions",
          "query": "identity.authorization.action:*delete"
         }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access Requests",
   "type": "graph",
   "description": "Authorization Activity",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Success", "query": "resultType:Success" },
         { "label": "Failure", "query": "resultType:Fail" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND operationName:*LISTKEYS* AND azure.category:Administrative AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "callerIpAddress.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      { "field": "select field", "id": "6", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Geo Activity",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 97 },
   "valueName": "total",
   "targets": [
    {
     "alias": "count",
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.latitude",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.longitude",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Caller IP",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "callerIpAddress.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.country_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "identity.claims.http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resource Type Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_type.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Caller IP",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "callerIpAddress.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure_subscription_name.keyword:$subscriptionname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Resource Groups by User",
   "type": "bargauge",
   "description": "Activity by Resource Group User",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND _exists_:identity.claims.name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Activated", "query": "resultType:Active" },
         {
          "label": "Resolved or Succeeded",
          "query": "resultType:Resolved OR resultType:Succeeded"
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Heatmap",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 130 },
   "format": "none",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "azure.provider.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 134 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Activated",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 134 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Resolved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 134 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "azure.resource_name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert AND resultType:Succeeded",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alerts Viewer",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "7",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "fake": true,
       "field": "azure.provider.keyword",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_group.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "azure.resource_name.keyword",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "resultDescription.keyword",
       "id": "13",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "resultType.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "30" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "durationMs",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "azure_subscription_name.keyword:$subscriptionname AND azure.group:activity_log AND azure.category:Alert",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}